name: Docker Publish

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - imageName: projector-webstorm:latest
            downloadLink: https://download.jetbrains.com/webstorm/WebStorm-2020.3.3.tar.gz
          - imageName: projector-idea-c:latest
            downloadLink: https://download.jetbrains.com/idea/ideaIC-2020.3.4.tar.gz
          - imageName: projector-idea-u:latest
            downloadLink: https://download.jetbrains.com/idea/ideaIU-2020.3.4.tar.gz
          - imageName: projector-clion:latest
            downloadLink: https://download.jetbrains.com/cpp/CLion-2020.3.4.tar.gz
          - imageName: projector-goland:latest
            downloadLink: https://download.jetbrains.com/go/goland-2020.3.5.tar.gz
          - imageName: projector-datagrip:latest
            downloadLink: https://download.jetbrains.com/datagrip/datagrip-2020.3.2.tar.gz
          - imageName: projector-phpstorm:latest
            downloadLink: https://download.jetbrains.com/webide/PhpStorm-2020.3.3.tar.gz
          - imageName: projector-pycharm-c:latest
            downloadLink: https://download.jetbrains.com/python/pycharm-community-2020.3.5.tar.gz
          - imageName: projector-pycharm-p:latest
            downloadLink: https://download.jetbrains.com/python/pycharm-professional-2020.3.5.tar.gz
          - imageName: projector-rider:latest
            downloadLink: https://download.jetbrains.com/rider/JetBrains.Rider-2020.3.4.tar.gz
          - imageName: projector-rubymine
            downloadLink: https://download.jetbrains.com/ruby/RubyMine-2020.3.4.tar.gz

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: projector-server

      - name: Checkout docker repo
        uses: actions/checkout@v2
        with:
          repository: JetBrains/projector-docker
          path: projector-docker

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - run: |
          cd projector-docker
          ./build-container.sh ${{ secrets.DOCKER_USERNAME }}/${{ matrix.imageName}} ${{ matrix.downloadLink }}
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ matrix.ImageName }}
